server:
  port: 8763

eureka:
  instance:
    prefer-ip-address: true   #访问路径现实IP地址
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/,http://localhost:6003/eureka/

description: producer-dev的自定义配置
