server:
  port: 8763

eureka:
  instance:
    prefer-ip-address: true   #访问路径现实IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka7001.com:6001/eureka/,http://eureka7002.com:6002/eureka/,http://eureka7003.com:6003/eureka/

description: producer-prod的自定义配置
